### PR TITLE
migrate from Travis to GHA and rework examples

### PR DESCRIPTION
**Pull request by eine**
On the one hand, the CI job is migrated from Travis to a GitHub Actions workflow.

On the other hand, examples are reworked:

- Subdir `examples` is created.
- Redundant files in `icezum` are removed.
- A test script to be used in ghdl/docker is added to `examples/icezum`.
- Redundant `echo "OK"` lines are removed from testsuites.

### CODE REVIEW

**Comment by tgingold** [comment]
I am not sure about removing the OK line.  That's useful when I run manually a single test.

**Comment by eine** [comment]
I'm ok with keeping them. But I think it should be consistent. This log is before removing them: https://github.com/eine/ghdlsynth-beta/commit/e8d9c2649bc5299f69e9d3d5a132c778690544ee/checks?check_suite_id=403873181 As you see, some have a single green OK (ghdl-issues/issue1000), but others have one non-coloured and one green (ghdl-issues/issue1001).

I am proposing to leave the green one only. But, as said, I am ok with adding the non-coloured one to the tests that are currently missing it.

**Comment by eine** [comment]
As commented by chat, I removed the conflicting modifications from this PR.

**Comment by tgingold** [comment]
Thanks.

**Pull request merged**
