### PR TITLE
Add shift functions

### PR DESCRIPTION
**Pull request by pepijndevos**
Does what it says on the tin.

Was also going to add memidx and dyn_extract, but can't really figure out how these are supposed to work and how they map to Yosys.

### CODE REVIEW

**Comment by tmeissner** [comment]
Hehe, have waited for https://github.com/tgingold/ghdlsynth-beta/issues/53#issuecomment-538653356 with my implementation, but okay. I will add a PR for Id_asr later, together with my tests.

**Comment by pepijndevos** [comment]
haha, okay. I was just about to add tests for this one. I'll let you handle it then :)

Uh... is this build failure something I did? Test pass locally, and didn't do anything particularly weird.

**Comment by 1138-4EB** [comment]
> Uh... is this build failure something I did? Test pass locally, and didn't do anything particularly weird.

@tgingold, can you please click the 'restart' button on the top right of https://travis-ci.com/tgingold/ghdlsynth-beta/builds/130548250?

@pepijndevos, this will check the changes that Tristan pushed in the last 18h.

**Comment by tgingold** [comment]
Done.  I will check as it could be my mistake.

**Comment by tgingold** [comment]
@pepijndevos, it was my mistake.  You can restart your build.

**Comment by tgingold** [comment]
Thanks!

**Pull request merged**
