### PR TITLE
Handle Const_X & Const_Z

### PR DESCRIPTION
**Pull request by tmeissner**
This a a pull request to try to handle Const_Z & Const_X. They are handled similar as Const_Bit, with the difference that all bits are set to 'Z' / 'X'.

### CODE REVIEW

**Comment by 1138-4EB** [comment]
This is already supported and tested by `ghdl --synth`, isn't it? I.e., no additional test is required neither here nor in ghdl/ghdl.

**Comment by tmeissner** [comment]
I think so, it works in tests with my SymbiYosys/GHDL setup.

**Comment by tgingold** [comment]
The code is correct, but you can directly call:
```
	SigSpec(RTLIL::State bit, int width = 1);
```

**Comment by tmeissner** [comment]
@tgingold You mean

```c++
return SigSpec(RTLIL::State::Sx, wd);
```

instead of

```c++
const unsigned wd = get_width(n);
std::vector<RTLIL::State> bits(wd);
for (unsigned i = 0; i < wd; i++) {
	bits[i] = RTLIL::State::Sx;
}
return RTLIL::SigSpec(RTLIL::Const(bits));
```
?

**Comment by tgingold** [comment]
Yes.  I think this should work but it is less code.

**Comment by tmeissner** [comment]
I've made the changes you suggested, so this should be ready to merge :)

**Comment by tgingold** [comment]
Thanks!  Ready to handle other missing gates ?

**Comment by tmeissner** [comment]
I have some code for other gates, I will make PR after some testing 🙂

**Pull request merged**
